name: Update Google Scholar Citations

on:
  schedule:
    - cron: '0 19 * * *'  # 每周一 03:00 UTC
  workflow_dispatch:

jobs:
  update-citations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install scholarly jsonpickle

    - name: Run update script
      run: python update_gs.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add results/gs_data.json
        git commit -m "Auto update citation count" || echo "No changes to commit"
        git push
