name: update_citations
on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:  # This allows manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # You can change this to another OS if needed

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Adjust to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r google_scholar_crawler/requirements.txt  # Assumes you have a requirements.txt file

    - name: Run the Python script
      run: python google_scholar_crawler/main.py

    - name: Set Git config
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Check for changes
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit and push changes
      run: |
        git pull
        git add .
        git commit -m "Update citations" || echo "No changes to commit"
        git push
